### ISSUE TITLE
ModuleNotFoundError: No module named 'termios' win10_64

### ISSUE THREAD

**Issue by Majestychen** [Einswilli/KivymdStudio#4]
F:\download\KivymdStudio-master>python39 studio.py
Traceback (most recent call last):
  File "F:\download\KivymdStudio-master\studio.py", line 7, in <module>
    from Terminal import*
  File "F:\download\KivymdStudio-master\Terminal.py", line 3, in <module>
    import fcntl, locale, os, pty, struct, sys, termios
  File "D:\python39\lib\pty.py", line 12, in <module>
    import tty
  File "D:\python39\lib\tty.py", line 5, in <module>
    from termios import *
ModuleNotFoundError: No module named 'termios'

**Comment by Einswilli** [comment]
try to remove the Terminal.py file from the project directory or comment the line 7 in studio.py file and rerun the project...
i hope this helps you!

**Comment by Einswilli** [comment]
you can also try pytyhon39 -m pip install termios
